spring.application.name=api-gateway

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8081/eureka


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG


spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true